engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  eslint:
    enabled: true
    channel: "eslint-3"
    exclude_fingerprints: 
    - 3facb0c8f4946ffe73740b559f75eb35  # Diable check 'Chart' is not defined.
  fixme:
    enabled: true
ratings:
  paths:
  - "src/**/*.js"
exclude_paths:
- dist/**/*
- node_modules/**/*
- test/**/*
- coverage/**/*
